include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/core/services/media_service.dart
    - lib/core/services/chat_service.dart
    - lib/core/services/firestore_service.dart
    - lib/core/services/dating_profile_service.dart
    - lib/core/services/auth_service.dart
    - lib/core/services/error_handler_service.dart
    - lib/core/services/push_notification_service.dart
    - lib/core/services/subscription_service.dart
    - lib/core/router/app_router.dart
    - _ignored/**
    - lib/_ignored/**
    - lib/_ignored/**
    - test/**
    # Providers still reference firebase/firestore packages you removed
    - lib/core/providers/**
    # If intl isn't in pubspec, exclude this utility
    - lib/core/utils/date_utils.dart
    # Template firebase options file (generated in real app, missing here)
    - lib/**/firebase_options_TEMPLATE.dart

  # Keep signal high: ignore noisy style infos while you stabilize build
  errors:
    deprecated_member_use: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_const_declarations: ignore
    dangling_library_doc_comments: ignore
    unused_import: ignore
