// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcBWiMjygiVoJ_X7BawAesfc3jJVotziM',
    appId: '1:327599352691:web:f298cda17b2ef78605b306',
    messagingSenderId: '327599352691',
    projectId: 'nexus-visibility-app',
    authDomain: 'nexus-visibility-app.firebaseapp.com',
    storageBucket: 'nexus-visibility-app.appspot.com',
    measurementId: 'G-LTMS3CH41D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf3dWHYiGPUj9Ul4wfqUQgmK2BpdSw-os',
    appId: '1:327599352691:android:ab5e0b946fb3a53105b306',
    messagingSenderId: '327599352691',
    projectId: 'nexus-visibility-app',
    storageBucket: 'nexus-visibility-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRXUOlD6BB6fPmDFHtbBykDI9mmO_zbYg',
    appId: '1:327599352691:ios:6592b5306dd82f3c05b306',
    messagingSenderId: '327599352691',
    projectId: 'nexus-visibility-app',
    storageBucket: 'nexus-visibility-app.appspot.com',
    iosBundleId: 'com.nexus4singles.nexusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRXUOlD6BB6fPmDFHtbBykDI9mmO_zbYg',
    appId: '1:327599352691:ios:ddd1141d47e32fd205b306',
    messagingSenderId: '327599352691',
    projectId: 'nexus-visibility-app',
    storageBucket: 'nexus-visibility-app.appspot.com',
    iosBundleId: 'com.nexus4singles.nexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcBWiMjygiVoJ_X7BawAesfc3jJVotziM',
    appId: '1:327599352691:web:00175e1eb0cdee2405b306',
    messagingSenderId: '327599352691',
    projectId: 'nexus-visibility-app',
    authDomain: 'nexus-visibility-app.firebaseapp.com',
    storageBucket: 'nexus-visibility-app.appspot.com',
    measurementId: 'G-9XM39EN16T',
  );
}
